// ROS message includes
#include "ros/ros.h"
#include <sensor_msgs/PointCloud2.h>

/* protected region user include files on begin */
/* protected region user include files end */

class beacon_pose_init_config
{
public:
    double x_object1;
    double y_object1;
    double x_object2;
    double y_object2;
    double x_init_pose;
    double y_init_pose;
    std::string base_beacon_link;
    std::string laser_beacon_link;
};

class beacon_pose_init_data
{
// autogenerated: don't touch this class
public:
    //input data
    sensor_msgs::PointCloud2 in_input;
    //output data
};

class beacon_pose_init_impl
{
    /* protected region user member variables on begin */
    /* protected region user member variables end */

public:
    beacon_pose_init_impl() 
    {
        /* protected region user constructor on begin */
        /* protected region user constructor end */
    }

    void configure(beacon_pose_init_config config) 
    {
        /* protected region user configure on begin */
        /* protected region user configure end */
    }

    void update(beacon_pose_init_data &data, beacon_pose_init_config config)
    {
        /* protected region user update on begin */
        /* protected region user update end */
    }

    void topicCallback_input(const sensor_msgs::PointCloud2::ConstPtr& msg)
    {
        /* protected region user implementation of subscribe callback for input on begin */
        /* protected region user implementation of subscribe callback for input end */
    }



    /* protected region user additional functions on begin */
    /* protected region user additional functions end */
};
